"""Remove username from user model

Revision ID: d711dac7ba23
Revises: f021192e9d90
Create Date: 2026-04-06 21:05:07.939249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # <- added this to use sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd711dac7ba23'
down_revision: Union[str, Sequence[str], None] = 'f021192e9d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###
